// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Session struct {
	SessionID   string `json:"session_id"`
	UserID      string `json:"user_id"`
	Expires     string `json:"expires"`
	DateCreated string `json:"date_created"`
}

type User struct {
	UserID         string `json:"user_id"`
	Name           string `json:"name"`
	Email          string `json:"email"`
	HashedPassword string `json:"hashed_password"`
	DateCreated    string `json:"date_created"`
	DateUpdated    string `json:"date_updated"`
}
