// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"
)

type Querier interface {
	// Create a new session for a user
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	// Delete a session by ID
	DeleteSessionByID(ctx context.Context, sessionID string) error
	// Delete a user by ID and hashed password
	DeleteUserByID(ctx context.Context, arg DeleteUserByIDParams) error
	// Get a session by ID
	GetSessionByID(ctx context.Context, sessionID string) (Session, error)
	// Get a user by email and hashed password
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Inset a new user
	InsertUser(ctx context.Context, arg InsertUserParams) (User, error)
	// Update a user by ID, this will also update the updated_at field in the database
	UpdateUserByID(ctx context.Context, arg UpdateUserByIDParams) error
}

var _ Querier = (*Queries)(nil)
